# Generated by Django 4.2 on 2023-05-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Maincategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(default='', max_length=20)),
                ('size', models.CharField(default='', max_length=30)),
                ('base_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(default=0)),
                ('pic1', models.ImageField(default='', upload_to='Product')),
                ('pic2', models.ImageField(blank=True, default='', null=True, upload_to='Product')),
                ('pic3', models.ImageField(blank=True, default='', null=True, upload_to='Product')),
                ('pic4', models.ImageField(blank=True, default='', null=True, upload_to='Product')),
                ('brands', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Mainapp.brands')),
                ('maincategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Mainapp.maincategory')),
                ('subcategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Mainapp.subcategory')),
            ],
        ),
    ]
