# Generated by Django 4.2 on 2023-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='pic2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Product'),
        ),
    ]
