# Generated by Django 4.2 on 2023-06-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_brands_pic2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('addressline1', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('addressline2', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('addressline3', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('pic', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
