# Generated by Django 4.2 on 2023-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='addressline1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='addressline2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='addressline3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
