# Generated by Django 4.2 on 2023-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_alter_buyer_addressline1_alter_buyer_addressline2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default='', max_length=30, null=True, upload_to=''),
        ),
    ]
