# Generated by Django 4.2 on 2023-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_alter_buyer_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='username',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
