# Generated by Django 4.2 on 2023-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0015_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
