# Generated by Django 4.2 on 2023-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0016_checkout_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='paymentStatus',
            field=models.IntegerField(choices=[(1, 'done'), (2, 'pending')], default=2),
        ),
    ]
