# Generated by Django 4.2 on 2023-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0017_alter_checkout_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='paymentStatus',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'done')], default=1),
        ),
    ]
