# Generated by Django 4.2 on 2023-07-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0020_support_querry'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=888888),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='paymentStatus',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'Paid')], default=1),
        ),
    ]
